// SPDX-License-Identifier: Apache-2.0

export type {
  ApiKeyId,
  AuthorizeRequest,
  ChangePasswordInput,
  ClientIdMetadataDocument,
  ClientIdMetadataUrl,
  ClientRegistrationInput,
  ConsentSubmission,
  ForgotPasswordInput,
  IssueApiKeyInput,
  LoginInput,
  OAuthClientIdParam,
  OAuthClientRegistrationMethod,
  ResendVerificationInput,
  ResetPasswordInput,
  SignupInput,
  TokenEndpointAuthMethod,
  TokenRequest,
  UserCredentials,
  VerifyEmailInput,
} from './auth.js'
export {
  apiKeyIdSchema,
  authorizeRequestSchema,
  changePasswordInputSchema,
  clientIdMetadataDocumentSchema,
  clientIdMetadataUrlSchema,
  clientRegistrationInputSchema,
  consentSubmissionSchema,
  forgotPasswordInputSchema,
  issueApiKeyInputSchema,
  loginInputSchema,
  oauthClientIdParamSchema,
  oauthClientRegistrationMethodSchema,
  redirectUriSchema,
  resendVerificationInputSchema,
  resetPasswordInputSchema,
  signupInputSchema,
  tokenEndpointAuthMethodSchema,
  tokenRequestSchema,
  userCredentialsSchema,
  verifyEmailInputSchema,
} from './auth.js'
// --- briefing/handoff bounds V2 (sectionLimit + sections, issue #45) ---
export type {
  BriefingSectionName,
  BriefingSelectorV2Input,
  BriefingToolArgsV2,
  BriefingToolArgsV3,
  BriefingToolInputV2,
  BriefingToolInputV3,
  BriefingToolOutputV2,
  BriefingToolOutputV3,
  HandoffCountsOutput,
  HandoffToolArgsV2,
  HandoffToolArgsV3,
  HandoffToolInputV2,
  HandoffToolInputV3,
  HandoffToolOutputV2,
  HandoffToolOutputV3,
  HandoffTruncatedOutput,
  ScopeProjectSelectorInput,
} from './briefing-bounds.js'
export {
  BRIEFING_SECTION_NAMES,
  briefingSectionNameSchema,
  briefingSelectorV2Schema,
  briefingToolInputV2Schema,
  briefingToolInputV3Schema,
  briefingToolOutputV2Schema,
  briefingToolOutputV3Schema,
  HANDOFF_SECTION_NAMES,
  handoffCountsSchema,
  handoffToolInputV2Schema,
  handoffToolInputV3Schema,
  handoffToolOutputV2Schema,
  handoffToolOutputV3Schema,
  handoffTruncatedSchema,
  MAX_BRIEFING_SECTION_CEILING,
  MAX_HANDOFF_SECTION_CEILING,
  scopeProjectSelectorSchema,
} from './briefing-bounds.js'
export type { BudgetStatusResponse, PlanTier } from './budget.js'
export { budgetStatusResponseSchema, PLAN_TIERS, planTierSchema } from './budget.js'
export type {
  CapabilityDescriptor,
  CapabilityDocument,
  CapabilityKind,
} from './capabilities.js'
export {
  capabilityDescriptorSchema,
  capabilityDocumentSchema,
  capabilityKindSchema,
} from './capabilities.js'
export type { CommitmentStatus } from './commitment.js'
export { COMMITMENT_TRANSITIONS, canTransition, commitmentStatusSchema } from './commitment.js'
export type { ConsolidationPolicy, ProposalStatus } from './consolidation.js'
export { CONSOLIDATION_POLICIES, proposalStatusSchema } from './consolidation.js'
export type { CursorPayload } from './cursor.js'
export { cursorPayloadSchema, legacyCursorPayloadSchema } from './cursor.js'
// --- get_memories batched bounded-content read (MCP tool IO) ---
export type {
  GetMemoriesArgs,
  GetMemoriesInput,
  GetMemoriesItemOutput,
  GetMemoriesOutput,
} from './get-memories.js'
export {
  DEFAULT_GET_CONTENT_CHARS,
  getMemoriesInputSchema,
  getMemoriesItemSchema,
  getMemoriesOutputSchema,
  MAX_GET_CONTENT_CHARS,
  MAX_GET_MEMORIES_IDS,
  MAX_GET_TOTAL_CHARS,
  MIN_GET_CONTENT_CHARS,
} from './get-memories.js'
// --- import write contracts (groundwork for batch importers) ---
export type {
  ImportCommitmentInput,
  ImportEdgeInput,
  ImportEventInput,
  ImportEventKind,
  ImportEventPayload,
  ImportFactInput,
  ImportMemoryInput,
} from './import.js'
export {
  importCommitmentSchema,
  importEdgeInputSchema,
  importEventInputSchema,
  importEventKindSchema,
  importEventPayloadSchema,
  importFactInputSchema,
  importMemoryInputSchema,
  importTimestampSchema,
  MAX_IMPORT_CONTENT_LENGTH,
  MAX_IMPORT_PAYLOAD_LENGTH,
} from './import.js'
// --- MCP tool IO (briefing/handoff orientation + search filters V2) — appended ---
export type {
  AsOfInput,
  BriefingCommitmentOutput,
  BriefingMemoryItemOutput,
  BriefingModeInput,
  BriefingSelectorInput,
  BriefingToolInput,
  BriefingToolOutput,
  ConfigureScopeInput,
  ConfigureScopeOutput,
  DescribeEnvironmentInput,
  DescribeEnvironmentOutput,
  EmbedStatus,
  FactOutput,
  FactsQueryArgs,
  FactsQueryInput,
  FactsToolOutput,
  HandoffCommitmentOutput,
  HandoffMemoryOutput,
  HandoffToolInput,
  HandoffToolOutput,
  ProposalRecordOutput,
  RememberToolArgs,
  RememberToolInput,
  RememberToolOutput,
  ResolveOutcomeStatus,
  ResolveToolInput,
  ResolveToolOutput,
  ReviewProposalsInput,
  ReviewProposalsOutput,
  ReviseToolArgs,
  ReviseToolInput,
  ReviseToolOutput,
  ScopeRecordOutput,
  SearchFiltersInput,
  SearchFiltersV2Input,
  SearchHitOutput,
  SearchInput,
  SearchQueryArgs,
  SearchQueryInput,
  SearchQueryV2Args,
  SearchQueryV2Input,
  SearchToolOutput,
  WrittenMemoryOutput,
} from './mcp.js'
// --- briefing/handoff orientation tool IO — appended ---
export {
  asOfSchema,
  briefingCommitmentSchema,
  briefingMemoryItemSchema,
  briefingModeSchema,
  briefingSelectorSchema,
  briefingToolInputSchema,
  briefingToolOutputSchema,
  configureScopeInputSchema,
  configureScopeOutputSchema,
  configureScopeRegisterOutputShape,
  configureScopeRegisterShape,
  DEFAULT_PROPOSALS_LIMIT,
  DEFAULT_SEARCH_LIMIT,
  describeEnvironmentInputSchema,
  describeEnvironmentOutputSchema,
  EXCERPT_MARKER,
  embedStatusSchema,
  factSchema,
  factsQueryInputSchema,
  factsToolOutputSchema,
  handoffCommitmentSchema,
  handoffMemorySchema,
  handoffToolInputSchema,
  handoffToolOutputSchema,
  MAX_EXCERPT_LENGTH,
  MAX_MEMORY_TYPES_FILTER,
  MAX_PROPOSALS_LIMIT,
  MAX_SCOPE_ALIASES,
  MAX_SEARCH_LIMIT,
  proposalRecordSchema,
  rememberToolInputSchema,
  rememberToolOutputSchema,
  resolveOutcomeStatusSchema,
  resolveToolInputSchema,
  resolveToolOutputSchema,
  reviewProposalsInputSchema,
  reviewProposalsOutputSchema,
  reviewProposalsRegisterOutputShape,
  reviewProposalsRegisterShape,
  reviseToolInputSchema,
  reviseToolOutputSchema,
  scopeAliasesSchema,
  scopeNameSchema,
  scopeRecordSchema,
  searchFiltersSchema,
  searchFiltersV2Schema,
  searchHitSchema,
  searchInputSchema,
  searchQuerySchema,
  searchQueryV2Schema,
  searchToolOutputSchema,
  writtenMemorySchema,
} from './mcp.js'
export type { ActorKind, EdgeType, EventKind, MemoryStatus, MemoryType } from './memory.js'
export {
  actorKindSchema,
  EDGE_TYPES,
  edgeTypeSchema,
  eventKindSchema,
  MEMORY_TYPES,
  memoryStatusSchema,
  memoryTypeSchema,
} from './memory.js'
// --- onboarding profiling ---
export type {
  ProfileAiTool,
  ProfileReferralSource,
  ProfileRole,
  ProfileUseCase,
  UserProfileAttributes,
} from './profile.js'
export {
  profileAiToolSchema,
  profileReferralSourceSchema,
  profileRoleSchema,
  profileUseCaseSchema,
  userProfileAttributesSchema,
} from './profile.js'
// --- shared recorded_at range rules (issue #58) ---
export type { RecordedRangeIssue } from './recorded-range.js'
export {
  exceedsRecordedBoundPrecision,
  MAX_RECORDED_BOUND_FRACTION_DIGITS,
  recordedRangeIssues,
} from './recorded-range.js'
export type { ResourceLimitKind, ResourceLimits } from './resource-limits.js'
export { resourceLimitKindSchema, resourceLimitsSchema } from './resource-limits.js'
// --- REST /api/v1 dashboard contract — appended block ---
export type {
  AccountDeleteBody,
  DashboardSearchHit,
  DashboardSearchQuery,
  DashboardSearchResponse,
  MemoriesFacetsResponse,
  MemoriesListQuery,
  MemoriesListResponse,
  MemoryDetail,
  MemoryHistoryEdge,
  MemoryHistoryEvent,
  MemoryHistoryEventPayloadMetadata,
  MemoryHistoryIdentity,
  MemoryHistoryLifecycleState,
  MemoryHistoryRelationship,
  MemoryHistoryResponse,
  MemoryListItem,
  MeResponse,
  ProposalRejectBody,
  ProposalsListQueryInput,
  RestErrorResponse,
  StatsResponse,
  VersionResponse,
} from './rest.js'
export {
  accountDeleteBodySchema,
  DEFAULT_DASHBOARD_SEARCH_LIMIT,
  DEFAULT_MEMORIES_LIMIT,
  DEFAULT_REST_PROPOSALS_LIMIT,
  dashboardSearchHitSchema,
  dashboardSearchQuerySchema,
  dashboardSearchResponseSchema,
  invalidInputRestErrorResponseSchema,
  MAX_DASHBOARD_SEARCH_LIMIT,
  MAX_MEMORIES_LIMIT,
  MAX_REST_ERROR_DETAIL_LENGTH,
  MAX_REST_PROPOSALS_LIMIT,
  memoriesFacetsResponseSchema,
  memoriesListQuerySchema,
  memoriesListResponseSchema,
  memoryDetailSchema,
  memoryHistoryEdgeSchema,
  memoryHistoryEventPayloadMetadataSchema,
  memoryHistoryEventSchema,
  memoryHistoryIdentitySchema,
  memoryHistoryLifecycleStateSchema,
  memoryHistoryRelationshipSchema,
  memoryHistoryResponseSchema,
  memoryListItemSchema,
  meResponseSchema,
  proposalRejectBodySchema,
  proposalsListQuerySchema,
  restErrorResponseSchema,
  statsResponseSchema,
  versionResponseSchema,
} from './rest.js'
// --- retrieval-scope policy (issue #47) — appended block ---
export type {
  BriefingToolOutputV4,
  ConfigureScopeInputV2,
  ConfigureScopeOutputV2,
  DashboardSearchResponseV2,
  DescribeEnvironmentOutputV2,
  HandoffToolOutputV4,
  RetrievalScopeMode,
  RetrievalScopePolicy,
  SearchRestResponseV2,
  SearchToolOutputV3,
  SetRetrievalDefaultInput,
} from './retrieval-scope.js'
export {
  briefingToolOutputV4Schema,
  configureScopeInputV2Schema,
  configureScopeOutputV2Schema,
  dashboardSearchResponseV2Schema,
  describeEnvironmentOutputV2Schema,
  handoffToolOutputV4Schema,
  retrievalScopeModeSchema,
  retrievalScopePolicySchema,
  retrievalScopePolicyScopeRequirements,
  searchRestResponseV2Schema,
  searchToolOutputV3Schema,
  setRetrievalDefaultInputSchema,
} from './retrieval-scope.js'
export type { Scope } from './scope.js'
export { DEFAULT_SCOPES, scopeSchema } from './scope.js'
// --- search cursor pagination + compact projection (MCP tool IO, issue #49) ---
export type {
  SearchHitCompactOutput,
  SearchProjection,
  SearchQueryV3Args,
  SearchQueryV3Input,
  SearchToolOutputV2,
} from './search-cursor.js'
export {
  searchHitCompactSchema,
  searchProjectionSchema,
  searchQueryV3Schema,
  searchToolOutputV2Schema,
} from './search-cursor.js'
export type {
  EdgeInput,
  FactWriteInput,
  Project,
  RememberInput,
  RememberWithFactsInput,
  ReviseEdgeIntent,
  ReviseInput,
  Tag,
} from './write.js'
export {
  edgeInputSchema,
  factWriteSchema,
  MAX_CONTENT_LENGTH,
  MAX_FACTS_PER_WRITE,
  MAX_TAG_LENGTH,
  MAX_TAGS,
  MAX_TOPIC_LENGTH,
  projectSchema,
  rememberInputSchema,
  rememberWithFactsInputSchema,
  reviseEdgeIntentSchema,
  reviseInputSchema,
  tagSchema,
} from './write.js'
