// SPDX-License-Identifier: Apache-2.0

export type {
  ApiKeyId,
  AuthorizeRequest,
  ChangePasswordInput,
  ClientIdMetadataDocument,
  ClientIdMetadataUrl,
  ClientRegistrationInput,
  ConsentSubmission,
  ForgotPasswordInput,
  IssueApiKeyInput,
  LoginInput,
  OAuthClientIdParam,
  OAuthClientRegistrationMethod,
  ResendVerificationInput,
  ResetPasswordInput,
  SignupInput,
  TokenEndpointAuthMethod,
  TokenRequest,
  UserCredentials,
  VerifyEmailInput,
} from './auth.js'
export {
  apiKeyIdSchema,
  authorizeRequestSchema,
  changePasswordInputSchema,
  clientIdMetadataDocumentSchema,
  clientIdMetadataUrlSchema,
  clientRegistrationInputSchema,
  consentSubmissionSchema,
  forgotPasswordInputSchema,
  issueApiKeyInputSchema,
  loginInputSchema,
  oauthClientIdParamSchema,
  oauthClientRegistrationMethodSchema,
  redirectUriSchema,
  resendVerificationInputSchema,
  resetPasswordInputSchema,
  signupInputSchema,
  tokenEndpointAuthMethodSchema,
  tokenRequestSchema,
  userCredentialsSchema,
  verifyEmailInputSchema,
} from './auth.js'
export type { BudgetStatusResponse, PlanTier } from './budget.js'
export { budgetStatusResponseSchema, PLAN_TIERS, planTierSchema } from './budget.js'
export type {
  CapabilityDescriptor,
  CapabilityDocument,
  CapabilityKind,
} from './capabilities.js'
export {
  capabilityDescriptorSchema,
  capabilityDocumentSchema,
  capabilityKindSchema,
} from './capabilities.js'
export type { CommitmentStatus } from './commitment.js'
export { COMMITMENT_TRANSITIONS, canTransition, commitmentStatusSchema } from './commitment.js'
export type { ConsolidationPolicy, ProposalStatus } from './consolidation.js'
export { CONSOLIDATION_POLICIES, proposalStatusSchema } from './consolidation.js'
export type { CursorPayload } from './cursor.js'
export { cursorPayloadSchema, legacyCursorPayloadSchema } from './cursor.js'
// --- import write contracts (groundwork for batch importers) ---
export type {
  ImportCommitmentInput,
  ImportEdgeInput,
  ImportEventInput,
  ImportEventKind,
  ImportEventPayload,
  ImportFactInput,
  ImportMemoryInput,
} from './import.js'
export {
  importCommitmentSchema,
  importEdgeInputSchema,
  importEventInputSchema,
  importEventKindSchema,
  importEventPayloadSchema,
  importFactInputSchema,
  importMemoryInputSchema,
  importTimestampSchema,
  MAX_IMPORT_CONTENT_LENGTH,
  MAX_IMPORT_PAYLOAD_LENGTH,
} from './import.js'
// --- briefing/handoff orientation tool IO + search filters V2 — appended ---
export type {
  AsOfInput,
  BriefingCommitmentOutput,
  BriefingMemoryItemOutput,
  BriefingModeInput,
  BriefingSelectorInput,
  BriefingToolInput,
  BriefingToolOutput,
  ConfigureScopeInput,
  ConfigureScopeOutput,
  DescribeEnvironmentInput,
  DescribeEnvironmentOutput,
  EmbedStatus,
  FactOutput,
  FactsQueryArgs,
  FactsQueryInput,
  FactsToolOutput,
  HandoffCommitmentOutput,
  HandoffMemoryOutput,
  HandoffToolInput,
  HandoffToolOutput,
  ProposalRecordOutput,
  RememberToolArgs,
  RememberToolInput,
  RememberToolOutput,
  ResolveOutcomeStatus,
  ResolveToolInput,
  ResolveToolOutput,
  ReviewProposalsInput,
  ReviewProposalsOutput,
  ReviseToolArgs,
  ReviseToolInput,
  ReviseToolOutput,
  ScopeRecordOutput,
  SearchFiltersInput,
  SearchFiltersV2Input,
  SearchHitOutput,
  SearchInput,
  SearchQueryArgs,
  SearchQueryInput,
  SearchQueryV2Args,
  SearchQueryV2Input,
  SearchToolOutput,
  WrittenMemoryOutput,
} from './mcp.js'
// --- briefing/handoff orientation tool IO — appended ---
export {
  asOfSchema,
  briefingCommitmentSchema,
  briefingMemoryItemSchema,
  briefingModeSchema,
  briefingSelectorSchema,
  briefingToolInputSchema,
  briefingToolOutputSchema,
  configureScopeInputSchema,
  configureScopeOutputSchema,
  configureScopeRegisterOutputShape,
  configureScopeRegisterShape,
  DEFAULT_PROPOSALS_LIMIT,
  DEFAULT_SEARCH_LIMIT,
  describeEnvironmentInputSchema,
  describeEnvironmentOutputSchema,
  EXCERPT_MARKER,
  embedStatusSchema,
  factSchema,
  factsQueryInputSchema,
  factsToolOutputSchema,
  handoffCommitmentSchema,
  handoffMemorySchema,
  handoffToolInputSchema,
  handoffToolOutputSchema,
  MAX_EXCERPT_LENGTH,
  MAX_MEMORY_TYPES_FILTER,
  MAX_PROPOSALS_LIMIT,
  MAX_SCOPE_ALIASES,
  MAX_SEARCH_LIMIT,
  proposalRecordSchema,
  rememberToolInputSchema,
  rememberToolOutputSchema,
  resolveOutcomeStatusSchema,
  resolveToolInputSchema,
  resolveToolOutputSchema,
  reviewProposalsInputSchema,
  reviewProposalsOutputSchema,
  reviewProposalsRegisterOutputShape,
  reviewProposalsRegisterShape,
  reviseToolInputSchema,
  reviseToolOutputSchema,
  scopeAliasesSchema,
  scopeNameSchema,
  scopeRecordSchema,
  searchFiltersSchema,
  searchFiltersV2Schema,
  searchHitSchema,
  searchInputSchema,
  searchQuerySchema,
  searchQueryV2Schema,
  searchToolOutputSchema,
  writtenMemorySchema,
} from './mcp.js'
export type { ActorKind, EdgeType, EventKind, MemoryStatus, MemoryType } from './memory.js'
export {
  actorKindSchema,
  EDGE_TYPES,
  edgeTypeSchema,
  eventKindSchema,
  MEMORY_TYPES,
  memoryStatusSchema,
  memoryTypeSchema,
} from './memory.js'
// --- onboarding profiling ---
export type {
  ProfileAiTool,
  ProfileReferralSource,
  ProfileRole,
  ProfileUseCase,
  UserProfileAttributes,
} from './profile.js'
export {
  profileAiToolSchema,
  profileReferralSourceSchema,
  profileRoleSchema,
  profileUseCaseSchema,
  userProfileAttributesSchema,
} from './profile.js'
export type { ResourceLimitKind, ResourceLimits } from './resource-limits.js'
export { resourceLimitKindSchema, resourceLimitsSchema } from './resource-limits.js'
// --- REST /api/v1 dashboard contract — appended block ---
export type {
  AccountDeleteBody,
  DashboardSearchHit,
  DashboardSearchQuery,
  DashboardSearchResponse,
  MemoriesFacetsResponse,
  MemoriesListQuery,
  MemoriesListResponse,
  MemoryDetail,
  MemoryHistoryEdge,
  MemoryHistoryEvent,
  MemoryHistoryEventPayloadMetadata,
  MemoryHistoryIdentity,
  MemoryHistoryLifecycleState,
  MemoryHistoryRelationship,
  MemoryHistoryResponse,
  MemoryListItem,
  MeResponse,
  ProposalRejectBody,
  ProposalsListQueryInput,
  StatsResponse,
} from './rest.js'
export {
  accountDeleteBodySchema,
  DEFAULT_DASHBOARD_SEARCH_LIMIT,
  DEFAULT_MEMORIES_LIMIT,
  DEFAULT_REST_PROPOSALS_LIMIT,
  dashboardSearchHitSchema,
  dashboardSearchQuerySchema,
  dashboardSearchResponseSchema,
  MAX_DASHBOARD_SEARCH_LIMIT,
  MAX_MEMORIES_LIMIT,
  MAX_REST_PROPOSALS_LIMIT,
  memoriesFacetsResponseSchema,
  memoriesListQuerySchema,
  memoriesListResponseSchema,
  memoryDetailSchema,
  memoryHistoryEdgeSchema,
  memoryHistoryEventPayloadMetadataSchema,
  memoryHistoryEventSchema,
  memoryHistoryIdentitySchema,
  memoryHistoryLifecycleStateSchema,
  memoryHistoryRelationshipSchema,
  memoryHistoryResponseSchema,
  memoryListItemSchema,
  meResponseSchema,
  proposalRejectBodySchema,
  proposalsListQuerySchema,
  statsResponseSchema,
} from './rest.js'
export type { Scope } from './scope.js'
export { DEFAULT_SCOPES, scopeSchema } from './scope.js'
export type {
  EdgeInput,
  Project,
  RememberInput,
  ReviseEdgeIntent,
  ReviseInput,
  Tag,
} from './write.js'
export {
  edgeInputSchema,
  MAX_CONTENT_LENGTH,
  MAX_TAG_LENGTH,
  MAX_TAGS,
  MAX_TOPIC_LENGTH,
  projectSchema,
  rememberInputSchema,
  reviseEdgeIntentSchema,
  reviseInputSchema,
  tagSchema,
} from './write.js'
