// SPDX-License-Identifier: Apache-2.0
// CLI reference generator: renders docs MDX from the
// CLI reference metadata and @3ngram/schema exports. This keeps the pre-1.0 CLI
// docs committed and freshness-checked beside the MCP/OpenAPI references.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  factsQueryInputSchema,
  factsToolOutputSchema,
  rememberToolInputSchema,
  rememberToolOutputSchema,
  searchQuerySchema,
  searchToolOutputSchema,
} from '@3ngram/schema'
import { z } from 'zod'
import {
  CLI_COMMANDS,
  CLI_ENV_VARS,
  CLI_GLOBAL_OPTIONS,
  type CliOptionReference,
} from '../src/reference.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const COMMANDS_SOURCE = resolve(HERE, '../src/commands.ts')
const OUT_FILE = resolve(HERE, '../../../docs/reference/cli.mdx')

const SCHEMAS = {
  remember: { input: rememberToolInputSchema, output: rememberToolOutputSchema },
  search: { input: searchQuerySchema.omit({ asOf: true }), output: searchToolOutputSchema },
  facts: { input: factsQueryInputSchema, output: factsToolOutputSchema },
} as const

function mdx(text: string): string {
  return text.replace(/[{<]/g, (char) => (char === '{' ? '&#123;' : '&lt;'))
}

function tableCell(text: string): string {
  return mdx(text).replace(/\|/g, '\\|')
}

function schemaBlock(schema: z.ZodType, io: 'input' | 'output'): string {
  const json = z.toJSONSchema(schema, { target: 'draft-2020-12', io, unrepresentable: 'any' })
  delete json.$schema
  return `\`\`\`json\n${JSON.stringify(json, null, 2)}\n\`\`\``
}

function frontmatter(): string {
  return [
    '---',
    'title: "CLI reference"',
    'description: "The 3ngram CLI commands, generated from CLI metadata and schema exports."',
    '---',
    '',
    '{/* GENERATED by apps/cli/scripts/generate-cli-reference.ts - do not edit by hand. */}',
  ].join('\n')
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  return [
    `| ${headers.map(tableCell).join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(tableCell).join(' | ')} |`),
  ].join('\n')
}

function optionName(option: CliOptionReference): string {
  const value = option.value === undefined ? '' : ` ${option.value}`
  return `\`${option.name}${value}\``
}

function optionRows(options: readonly CliOptionReference[]): string[][] {
  return options.map((option) => [
    optionName(option),
    option.required === true ? 'yes' : 'no',
    option.repeatable === true ? 'yes' : 'no',
    option.description,
  ])
}

function assertCommandCoverage(): void {
  const source = readFileSync(COMMANDS_SOURCE, 'utf8')
  const implemented = new Set([...source.matchAll(/case '([^']+)'/g)].map((match) => match[1]))
  const documented = new Set(CLI_COMMANDS.map((command) => command.name))
  const missing = [...implemented].filter((name) => !documented.has(name))
  const stale = [...documented].filter((name) => !implemented.has(name))
  if (missing.length > 0 || stale.length > 0) {
    throw new Error(
      `cli reference out of sync with commands.ts - missing: [${missing.join(', ')}] stale: [${stale.join(', ')}]`,
    )
  }
}

function renderCommand(command: (typeof CLI_COMMANDS)[number]): string {
  const inputSchema = SCHEMAS[command.requestSchema].input
  const outputSchema = SCHEMAS[command.responseSchema].output
  return [
    `### ${command.name}`,
    '',
    mdx(command.summary),
    '',
    `**Usage:** \`3ngram ${command.usage.trim()}\`  `,
    `**SDK call:** \`${command.sdkCall}\``,
    '',
    '### Options',
    '',
    table(['Option', 'Required', 'Repeatable', 'Description'], optionRows(command.options)),
    '',
    '### Examples',
    '',
    ...command.examples.flatMap((example) => [`\`\`\`bash\n${example}\n\`\`\``, '']),
    '### Input payload schema',
    '',
    schemaBlock(inputSchema, 'input'),
    '',
    '### Output schema',
    '',
    schemaBlock(outputSchema, 'output'),
  ].join('\n')
}

function render(): string {
  return [
    frontmatter(),
    '',
    'The `3ngram` CLI is a thin command-line client over `@3ngram/sdk` and the REST `/api/v1` surface. Install it with `npm install -g 3ngram` (or run one-off commands via `npx 3ngram`); local source runs can use `node apps/cli/dist/index.js` after building the package.',
    '',
    '<Note>',
    'The CLI uses API keys, not MCP OAuth. Pass `--api-key` or set `THREENGRAM_API_KEY`; the key is sent as `X-API-Key` and is never printed in error output.',
    '</Note>',
    '',
    '## Configuration',
    '',
    'Flags override environment variables. `--base-url` expects the REST origin without `/api/v1`.',
    '',
    table(
      ['Name', 'Description'],
      [...CLI_GLOBAL_OPTIONS, ...CLI_ENV_VARS].map((option) => [
        optionName(option),
        option.description,
      ]),
    ),
    '',
    '## Commands',
    '',
    CLI_COMMANDS.map(renderCommand).join('\n\n'),
    '',
    '## Exit behavior',
    '',
    '- `0`: command completed successfully.',
    '- `1`: no command was supplied, the server rejected the request, or the transport failed.',
    '- `2`: CLI usage or configuration error, including missing required flags.',
    '',
  ].join('\n')
}

function main(): void {
  assertCommandCoverage()
  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, render())
  process.stdout.write(`cli-reference: wrote ${CLI_COMMANDS.length} commands to ${OUT_FILE}\n`)
}

main()
