// SPDX-License-Identifier: Apache-2.0
// NOTE: biome organizeImports keeps these export statements sorted by source.
// consolidate/surface and their repos live in the './admin/index.js' re-export
// block below.
// --- account lifecycle: self-serve deletion ---

export { assertRlsInForce, ResourceLimitExceededError, RlsGuardError } from '@3ngram/db'
// --- budget: access gate port + Apache budget gate ---
export type {
  ResourceLimitKind,
  ResourceLimits,
} from '@3ngram/schema'
// The hard briefing/handoff sectionLimit ceilings (bounds V2) — re-exported so
// core consumers see the ACTUAL max next to the defaults
// MAX_BRIEFING_SECTION / MAX_HANDOFF_SECTION below.
export { MAX_BRIEFING_SECTION_CEILING, MAX_HANDOFF_SECTION_CEILING } from '@3ngram/schema'
export {
  type AccountDeletionResult,
  type AccountErasureResult,
  type DeleteAccountOptions,
  deleteAccount,
} from './account/index.js'
export {
  type AllProposals,
  type AppliedProposalRow,
  acceptProposalAnyKind,
  applyProposal,
  CLOSER_ACTOR_KIND,
  CLOSER_EVENTS_PAGE_SIZE,
  CLOSER_OPERATION,
  type CloserClaim,
  type CloserEnqueueRequest,
  type CloserEventPage,
  type CloserEventSummary,
  type CloserFinish,
  type CloserOptions,
  type CloserResult,
  type CloserSessionInput,
  type CloserSkipReason,
  CloserVerdictError,
  type ConsolidateOptions,
  type ConsolidateRepo,
  type ConsolidateResult,
  chooseProposedEdge,
  closeSessionRun,
  consolidate,
  DEFAULT_CONSOLIDATION_LIMIT,
  DEFAULT_CONSOLIDATION_SIMILARITY,
  type DecidedProposal,
  dbConsolidateRepo,
  dbGcClientsRepo,
  dbSessionCloserRepo,
  dbSessionSweepRepo,
  dbSurfacingRepo,
  describeEnvironment,
  type EnvironmentReport,
  type EnvironmentStats,
  EpisodicSupersessionError,
  type FactProposalRecord,
  GC_CLIENT_IDLE_DAYS,
  type GcClientsOptions,
  type GcClientsRepo,
  type GcClientsResult,
  garbageCollectClients,
  isCloserEligible,
  listAllProposals,
  listProposals,
  ProposalNotFoundError,
  type ProposalRecord,
  type ProposalsListQuery,
  rejectProposal,
  rejectProposalAnyKind,
  renderCloserPrompt,
  type SessionCloserRepo,
  type SessionSweepOptions,
  type SessionSweepRepo,
  type SessionSweepResult,
  SuccessorNotLiveError,
  type SurfacingRepo,
  type SurfacingResult,
  selectResolvable,
  surface,
  sweepSessions,
} from './admin/index.js'
export {
  createUser,
  DuplicateEmailError,
  hashPassword,
  type ProvisionedUser,
  verifyPassword,
} from './auth/index.js'
export {
  AccessDeniedError,
  type AccessGate,
  allowAllAccess,
  assertWithinBudget,
  type BudgetConfig,
  type BudgetEnforcement,
  BudgetExceededError,
  type BudgetLogger,
  type BudgetReservationHandle,
  type BudgetStatus,
  getBudgetStatus,
  type Limits,
  type LimitsResolver,
  releaseBudgetReservation,
  reserveBudgetSlot,
  resolveResourceLimits,
  SELFHOST_LIMITS,
} from './budget/index.js'
// --- import facade (groundwork for batch importers) ---
export {
  IMPORT_EMBED_OPERATION,
  ImportTargetNotFoundError,
  type ImportWriteOptions,
  importEdge,
  importEvent,
  importFact,
  importMemory,
} from './import/index.js'
// --- product prompt text, shared by every transport that renders it ---
export {
  type DebriefBriefedMemory,
  type DebriefPromptContext,
  renderDebriefPrompt,
} from './prompts/index.js'
export {
  type AsOf,
  applyPolicyToScopeFilter,
  applyPolicyToSelector,
  type Briefing,
  type BriefingCommitment,
  type BriefingMemoryItem,
  type BriefingMode,
  type BriefingQuery,
  type BriefingSection,
  type BriefingSelector,
  briefing,
  type DashboardPageOptions,
  type DashboardSearchPage,
  DEFAULT_BRIEFING_TOP,
  DEFAULT_SEARCH_SUPERSESSION_PENALTY,
  DEFAULT_SEARCH_WEIGHTS,
  type EmbeddingSource,
  EmptySectionsError,
  type ExportAccountRow,
  type ExportAgentSessionRow,
  type ExportBudgetRow,
  type ExportCommitmentRow,
  type ExportEdgeRow,
  type ExportEnricher,
  type ExportFactProposalRow,
  type ExportFactRow,
  type ExportLlmUsageRow,
  type ExportMemoryEventRow,
  type ExportMemoryRow,
  type ExportProposalRow,
  type ExportScopeRow,
  type ExportUserProfileRow,
  exportUserData,
  type FactRow,
  type FactsQuery,
  type FrozenOrdering,
  type FullBriefing,
  type FusionWeights,
  formatUnscopedRetrievalDetail,
  type GetMemoriesOptions,
  getCurrentUser,
  getFacts,
  getMemoriesByIds,
  getMemoryById,
  getMemoryHistory,
  type Handoff,
  type HandoffCommitment,
  type HandoffMemory,
  type HandoffQuery,
  handoff,
  InvalidEmbeddingError,
  type ListOptions,
  type ListPage,
  type ListSessionEventsOptions,
  listMemories,
  listMemoryFacets,
  listSessionEvents,
  MAX_BRIEFING_SECTION,
  MAX_HANDOFF_SECTION,
  type MemoriesBatchRead,
  type MemoriesListQuery,
  type MemoriesPage,
  type MemoryBatchItem,
  type MemoryDetailRow,
  type MemoryFacets,
  type MemoryHistoryRead,
  type MemoryListRow,
  MemoryNotFoundError,
  MissingSelectorError,
  type RetrievalPolicy,
  requireSelector,
  type ScopedSearchResult,
  type SearchHit,
  type SearchOptions,
  type SessionEventRow,
  type SessionEventsPage,
  STALE_CANDIDATE_TYPES,
  STALE_WINDOW_DAYS,
  search,
  searchChronological,
  searchDashboardPage,
  UnscopedRetrievalError,
  type UserDataExport,
  type UserIdentityRow,
} from './read/index.js'
// --- MCP admin tools: scopes + proposals + environment ---
export {
  createScope,
  deleteScope,
  listScopes,
  type RetrievalPolicySetting,
  renameScope,
  resolveRetrievalPolicy,
  ScopeNameConflictError,
  ScopeNotFoundError,
  type ScopeRecord,
  setRetrievalDefault,
  setScopeAliases,
} from './scope/index.js'
// --- hook-facing agent-session bookkeeping: open / close / heartbeat / triage ---
export {
  AgentSessionNotFoundError,
  AgentSessionParamsConflictError,
  type AgentSessionRecord,
  AgentSessionTriageConflictError,
  type BeginTriageFacadeOptions,
  type BeginTriageOptions,
  type BeginTriageResult,
  beginAgentSessionTriage,
  type CloseSessionResult,
  type CompleteTriageResult,
  closeAgentSession,
  completeAgentSessionTriage,
  evaluateTriageEntry,
  getAgentSession,
  type HeartbeatSessionResult,
  heartbeatAgentSession,
  type OpenSessionResult,
  openAgentSession,
  type SessionClockOptions,
  type TriageDebounceThresholds,
  type TriageEntryDecision,
} from './session/index.js'
export {
  archiveMemory,
  BlockerNotFoundError,
  type ClosedRunResolveOutcome,
  CommitmentExistsError,
  CommitmentNotFoundError,
  CommitmentStateChangedError,
  type CreateCommitmentOptions,
  createCommitment,
  DuplicateMemoryError,
  EdgeConflictError,
  IllegalCommitmentTransitionError,
  InvalidCommitmentTransitionError,
  NotCommitmentMemoryError,
  PredecessorAlreadySupersededError,
  PredecessorNotFoundError,
  type ResolveStatus,
  type RetryFailedEmbedsOptions,
  type RetryFailedEmbedsResult,
  remember,
  resolveByMemoryId,
  retryFailedEmbeds,
  revise,
  transition,
  UnknownSessionRunError,
  type WrittenCommitment,
} from './write/index.js'
