// SPDX-License-Identifier: Apache-2.0
// Code generated by scripts/gen-hook-contract.mjs. DO NOT EDIT.
//
// The bounds cmd/3ngram-hook must honour BEFORE it builds a request body,
// mirrored from packages/schema (the single validation boundary, AGENTS.md hard
// rule 2). Regenerate with `pnpm run docs:generate`; the docs-reference CI lane
// diffs this file byte for byte, so a schema change that is not regenerated
// here goes red.
//
// CONSTANTS ONLY. Shape validation (agent-name kebab-case, uuid form, enum
// membership) is deliberately NOT mirrored: the server's Zod parse is the one
// validator for those, and a Go copy would be a second boundary that can
// silently disagree with it.
package main

const (
	// MAX_SESSION_EXCERPT_LENGTH.
	// Upper bound on `lastMessageExcerpt`. The server 400s a longer excerpt
	// rather than deciding which half of an agent's message matters, and a 400
	// on Stop would cost the turn its lease refresh — so the hook truncates to
	// this before sending.
	maxSessionExcerptLength = 4000

	// MAX_BRIEFED_MEMORIES.
	// Cap on the `briefedMemories` array the SessionStart open stamps. Past it
	// the whole open 400s and the session loses its sessionRunId, so the hook
	// stops collecting rather than trading every row for the last one.
	maxBriefedMemories = 100

	// MAX_BRIEFING_SECTION_CEILING.
	// Largest `sectionLimit` the briefing GET accepts. `commitments list` asks
	// for exactly this, so `hasMore` is the only reason a row can be missing;
	// one past it would 400 the whole read.
	maxBriefingSectionCeiling = 100

	// MAX_REST_PROPOSALS_LIMIT.
	// Largest `limit` GET /api/v1/proposals accepts. `commitments show` reads
	// this many pending proposals and reports the window it inspected, since a
	// bounded tenant-wide list cannot prove no evidence exists.
	maxRestProposalsLimit = 100
)
