// SPDX-License-Identifier: Apache-2.0
// SDK reference generator: renders docs MDX from the
// public SDK method metadata and @3ngram/schema exports. The generated page is a
// committed reference artifact and is checked by the docs freshness gate.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  commitmentStatusSchema,
  factsQueryInputSchema,
  factsToolOutputSchema,
  rememberToolInputSchema,
  rememberToolOutputSchema,
  resolveToolOutputSchema,
  reviseToolInputSchema,
  reviseToolOutputSchema,
  searchQuerySchema,
  searchRestResponseV2Schema,
} from '@3ngram/schema'
import { z } from 'zod'
import { SDK_ERRORS, SDK_METHODS } from '../src/reference.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const CLIENT_SOURCE = resolve(HERE, '../src/client.ts')
const OUT_FILE = resolve(HERE, '../../../docs/reference/sdk.mdx')

const SCHEMAS = {
  remember: { input: rememberToolInputSchema, output: rememberToolOutputSchema },
  search: { input: searchQuerySchema, output: searchRestResponseV2Schema },
  facts: { input: factsQueryInputSchema, output: factsToolOutputSchema },
  revise: {
    input: reviseToolInputSchema.omit({ predecessorId: true }),
    output: reviseToolOutputSchema,
  },
  resolve: {
    input: z.object({ status: commitmentStatusSchema }).strict(),
    output: resolveToolOutputSchema,
  },
} as const

function mdx(text: string): string {
  return text.replace(/[{<]/g, (char) => (char === '{' ? '&#123;' : '&lt;'))
}

function tableCell(text: string): string {
  return mdx(text).replace(/\\/g, '\\\\').replace(/\|/g, '\\|')
}

function schemaBlock(schema: z.ZodType, io: 'input' | 'output'): string {
  const json = z.toJSONSchema(schema, { target: 'draft-2020-12', io, unrepresentable: 'any' })
  delete json.$schema
  return `\`\`\`json\n${JSON.stringify(json, null, 2)}\n\`\`\``
}

function frontmatter(): string {
  return [
    '---',
    'title: "SDK reference"',
    'description: "The @3ngram/sdk client surface, generated from SDK metadata and schema exports."',
    '---',
    '',
    '{/* GENERATED by packages/sdk/scripts/generate-sdk-reference.ts - do not edit by hand. */}',
  ].join('\n')
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  return [
    `| ${headers.map(tableCell).join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(tableCell).join(' | ')} |`),
  ].join('\n')
}

function assertMethodCoverage(): void {
  const source = readFileSync(CLIENT_SOURCE, 'utf8')
  const classBody = source.slice(source.indexOf('export class ThreengramClient'))
  const implemented = new Set(
    [...classBody.matchAll(/^ {2}([A-Za-z][A-Za-z0-9]*)\(/gm)]
      .map((match) => match[1])
      .filter((name) => name !== 'constructor'),
  )
  const documented = new Set(SDK_METHODS.map((method) => method.name))
  const missing = [...implemented].filter((name) => !documented.has(name))
  const stale = [...documented].filter((name) => !implemented.has(name))
  if (missing.length > 0 || stale.length > 0) {
    throw new Error(
      `sdk reference out of sync with client.ts - missing: [${missing.join(', ')}] stale: [${stale.join(', ')}]`,
    )
  }
}

function renderMethod(method: (typeof SDK_METHODS)[number]): string {
  const inputSchema = SCHEMAS[method.requestSchema].input
  const outputSchema = SCHEMAS[method.responseSchema].output
  return [
    `### ${method.name}`,
    '',
    mdx(method.summary),
    '',
    `**Signature:** \`${method.signature}\`  `,
    `**REST route:** \`${method.route}\``,
    '',
    '### Example',
    '',
    `\`\`\`ts\n${method.example}\n\`\`\``,
    '',
    '### Input schema',
    '',
    schemaBlock(inputSchema, 'input'),
    '',
    '### Output schema',
    '',
    schemaBlock(outputSchema, 'output'),
  ].join('\n')
}

function render(): string {
  return [
    frontmatter(),
    '',
    '`@3ngram/sdk` is a thin TypeScript client over the REST `/api/v1` surface. It takes explicit configuration and sends the configured API key as `X-API-Key` on every request.',
    '',
    '<Note>',
    'Install with `npm install @3ngram/sdk` (or `pnpm add @3ngram/sdk`). The package ships ESM with bundled type declarations.',
    '</Note>',
    '',
    '## Client setup',
    '',
    '```ts',
    "import { ThreengramClient } from '@3ngram/sdk'",
    '',
    'const apiKey = process.env.THREENGRAM_API_KEY',
    "if (apiKey === undefined) throw new Error('missing THREENGRAM_API_KEY')",
    '',
    'const client = new ThreengramClient({',
    "  baseUrl: 'https://api.3ngram.ai',",
    '  apiKey,',
    '})',
    '```',
    '',
    table(
      ['Config', 'Description'],
      [
        ['`baseUrl`', 'REST origin without `/api/v1`. Trailing slashes are trimmed.'],
        ['`apiKey`', 'API key sent as the `X-API-Key` header. The SDK has no env fallback.'],
      ],
    ),
    '',
    '## Methods',
    '',
    SDK_METHODS.map(renderMethod).join('\n\n'),
    '',
    '## Errors',
    '',
    table(
      ['Error', 'Description'],
      SDK_ERRORS.map((error) => [`\`${error.name}\``, error.description]),
    ),
    '',
  ].join('\n')
}

function main(): void {
  assertMethodCoverage()
  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, render())
  process.stdout.write(`sdk-reference: wrote ${SDK_METHODS.length} methods to ${OUT_FILE}\n`)
}

main()
