// SPDX-License-Identifier: Apache-2.0
// MCP reference generator: renders docs MDX from
// the typed TOOLS registry and the PROMPTS registry. Hand-written tool pages
// drift from the registry, so hand-written MCP
// reference pages are BANNED; these files are committed build artifacts and CI
// regenerates + diffs them (freshness gate).
//
// INCLUSION DECISION: the full registered surface is documented — the 5 core
// tools, the 2 orientation tools (briefing/handoff), get_memories (inspect), and
// the 3 admin tools (configure_scope/describe_environment/review_proposals). All
// eleven are served to every authenticated MCP client (scope floors gate
// handlers, not visibility), so all eleven are public reference. One page per
// surface (tools.mdx, prompts.mdx) keeps docs.json navigation static.
//
// NO COUNT ASSERTION HERE. This generator used to throw above a fixed tool and
// prompt ceiling. The surface is now gated on what those numbers proxied for —
// selection accuracy and description overlap, measured by
// eval/src/tool-selection.mjs against eval/fixtures/floors.json — so a docs build
// is the wrong place to relitigate a count it cannot measure.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { McpServer } from '@modelcontextprotocol/server'
import { z } from 'zod'
import { PROMPTS } from '../src/mcp/prompts.js'
import { TOOLS } from '../src/mcp/tools.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = resolve(HERE, '../../../docs/reference')

/** Escape the MDX-significant characters that may appear in registry prose. */
function mdx(text: string): string {
  return text.replace(/[{<]/g, (char) => (char === '{' ? '&#123;' : '&lt;'))
}

/**
 * Render a tool/prompt schema as a fenced JSON Schema block (draft 2020-12).
 * SDK v2 registry entries carry full Standard Schema objects. The 3ngram
 * registry uses Zod, so render those canonical objects directly and preserve
 * strict/discriminated-union semantics in the generated reference.
 */
function schemaBlock(schema: z.ZodType, io: 'input' | 'output'): string {
  const json = z.toJSONSchema(schema, { target: 'draft-2020-12', io })
  delete json.$schema
  return `\`\`\`json\n${JSON.stringify(json, null, 2)}\n\`\`\``
}

function frontmatter(title: string, description: string): string {
  return [
    '---',
    `title: "${title}"`,
    `description: "${description}"`,
    '---',
    '',
    '{/* GENERATED by apps/server/scripts/generate-mcp-reference.ts - do not edit by hand. */}',
  ].join('\n')
}

function renderTools(): string {
  const sections = TOOLS.map((tool) => {
    const floor = tool.requiredScope
    const scopes = typeof floor === 'string' ? floor : floor.anyOf.join('` or `')
    return [
      `## ${tool.name}`,
      '',
      mdx(tool.config.description),
      '',
      `**Title:** ${mdx(tool.config.title)} · **Required scope:** \`${scopes}\``,
      '',
      '### Input schema',
      '',
      schemaBlock(tool.config.inputSchema, 'input'),
      '',
      '### Output schema',
      '',
      schemaBlock(tool.config.outputSchema, 'output'),
    ].join('\n')
  })
  return [
    frontmatter(
      'MCP tools',
      `The ${TOOLS.length} registered MCP tools, generated from the typed TOOLS registry.`,
    ),
    '',
    `The 3ngram MCP server registers ${TOOLS.length} tools. The surface is kept small by measurement rather than a fixed ceiling: a blocking eval gates tool-selection accuracy and description overlap, so a new tool has to route cleanly against the existing ones. Every tool validates against the schemas below; scope floors are enforced per call.`,
    '',
    sections.join('\n\n'),
    '',
  ].join('\n')
}

interface CapturedPrompt {
  name: string
  title: string
  description: string
  argsSchema: z.ZodType
}

/**
 * The prompt registry erases config behind a server-bound registrar, so capture
 * it by registering each prompt onto a stub that records instead of serving.
 */
function capturePrompts(): CapturedPrompt[] {
  const captured: CapturedPrompt[] = []
  const stub = {
    registerPrompt(
      name: string,
      config: { title: string; description: string; argsSchema: z.ZodType },
    ): void {
      captured.push({ name, ...config })
    },
  }
  for (const prompt of PROMPTS) prompt.register(stub as unknown as McpServer)
  return captured
}

function renderPrompts(prompts: CapturedPrompt[]): string {
  const sections = prompts.map((prompt) =>
    [
      `## ${prompt.name}`,
      '',
      mdx(prompt.description),
      '',
      `**Title:** ${mdx(prompt.title)}`,
      '',
      '### Arguments',
      '',
      schemaBlock(prompt.argsSchema, 'input'),
    ].join('\n'),
  )
  return [
    frontmatter(
      'MCP prompts',
      `The ${prompts.length} code-defined MCP prompts, generated from the PROMPTS registry.`,
    ),
    '',
    `The server ships ${prompts.length} code-defined prompts. A prompt only orients the agent — it never queries or persists; arguments arrive as strings over the MCP wire.`,
    '',
    sections.join('\n\n'),
    '',
  ].join('\n')
}

function main(): void {
  const prompts = capturePrompts()
  mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(resolve(OUT_DIR, 'tools.mdx'), renderTools())
  writeFileSync(resolve(OUT_DIR, 'prompts.mdx'), renderPrompts(prompts))
  process.stdout.write(`mcp-reference: wrote ${TOOLS.length} tools + ${prompts.length} prompts\n`)
}

main()
